version: "3"

services:
  wait:
    image: hello-world:latest
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=newsletter
    ports:
      - '5432:5432'
    volumes: 
      - data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - RUST_LOG=info
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=newsletter
      - DB_HOST=database
      - DB_PORT=5432
      - APP_PORT=8081
    depends_on:
      database:
        condition: service_healthy

volumes:
  data:

networks:
  app-network:
    driver: bridge
