
name: Testing 

on:
  push:
    branches:
      - dev
    paths:
      - "**.rs"
      - "Cargo.*"
      - ".github/workflows/testing.yml"
  pull_request:
    paths:
      - "**.rs"
      - "Cargo.*"
      - ".github/workflows/testing.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./
    
    env:
      DB_NAME: newsletter 

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    
    - name: test runner
      uses: taiki-e/install-action@v2
      with:
        tool: nextest

    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman
        sudo apt-get install -y pipx
        pipx install podman-compose

    - name: Cache dependencies
      uses: actions/cache@v3
      env:
        cache-name: cache-dependencies
      with:
        path: |
          ~/.cargo
          newsletter/target
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Start database
      run: make up 

    - name: Run integration tests
      run: make test-integration

    - name: Run lib tests
      run: make test-lib

    - name: Start backend service
      run: make down start-backend
    
    - name: Tear Down
      run: make down

